# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sirius CTF
tagline:          'CTF'
description:      'CTF Write-ups and programming'
url:              http://taishi8117.github.io
baseurl:          /

author:
  name:           'Taishi Nojima'
  url:            https://taishi8117.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
